config/routes.rb
Rails.application.routes.draw do

  authenticated :user do
    root to: 'pages#console', as: :authenticated_root
  end

  unauthenticated do
    root to: 'pages#radar', as: :unauthenticated_root
  end

  resources :fields

  resources :users, only: [:show] do
    resources :goals, only: [:new, :create]
    resources :calendars
    member do
      post '/verify_phone_number' => 'users#verify_phone_number'
      patch 'update_phone_number' => 'users#update_phone_number'
      put 'follow' => 'users#follow'
      put 'unfollow' => 'users#unfollow'
      get 'clubs'
      get 'calledup'
      get 'view'
      get 'referee'
      get 'preview'
    end
  end
  resources :referees do
    member do
      get 'feed'
    end
  end
  resource :relationships, only: [:create, :destroy]
  resources :clubs, except: [:edit] do
    resources :invitations, only: [:new, :create]
    resources :calendars
    member do
      get 'edit'
      get 'duels'
      get 'members'
      get 'location'
      get 'scouting'
      get 'requests'
      get 'direction'
    end

    get 'join', on: :member
    get 'jointrue', on: :member
    post 'mark_all_as_read'
    post 'sendjoin/:user_id', to: 'clubs#sendjoin', as: 'sendjoin'
    post 'selfjoin/:user_id', to: 'clubs#selfjoin', as: 'selfjoin'

    resources :club_photos, only: [:create, :destroy]
    resources :memberships, only: [:create, :destroy, :edit, :update, :approve, :decline, :show] do 
      
      member do 
        post 'approve'
        get 'approve' 
        post 'decline' 
        get 'decline' 
      end
    end
    
    resources :duels do
      post :send_invitation, on: :member
      post 'join', on: :member
      get 'referee_access', on: :member
      get 'joinlines', on: :member
      resources :reservations, except: [:index, :new, :create]
      resources :invitations
      resources :duel_photos, only: [:create, :destroy]
      resources :rivals do
        post 'challenge', on: :collection
      end
      resources :reservations do 
        get 'reply'
      end
      resources :lines, only: [:create, :destroy, :edit, :update, :invoke, :ejected, :show] do 
        get 'join', on: :member
        get 'joinlines', on: :member
        member do 
          post '/invoke' => "lines#invoke"
          post '/ejected' => "lines#ejected"
        end
      end
      member do
        get 'front'
        get 'budget'
        get 'referee'
        get 'location'
        get 'panel'
        get 'members'
        get 'formation'
        get 'assignment'
        get 'control'
      end
    end
  end

  devise_for :users,
              path: '',
              path_names: {
                sign_in: 'login', 
                sign_out: 'logout', 
                edit: 'users/:id/edit',
                sign_up: 'registration' 
              }, 
              controllers: {
                omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations'
              }

  resources :notifications do
    member do
      patch :mark_as_read
    end
    
    collection do
      patch :mark_all_as_read
    end
  end



  get 'live' => 'pages#live'
  get 'radar' => 'pages#radar'
  get 'search' => 'pages#search'
  get 'battle' => 'pages#battle'
  get 'explore' => 'pages#explore'
  get 'console' => 'pages#console'
  get 'players' => 'pages#players'
  get 'notifications' => 'pages#notifications'
  get 'preload_tasks', to: 'pages#preload_tasks'
  get 'clubname_validator/:slug', to: 'clubs#clubname_validator'
  get 'username_validator/:slug', to: 'users#username_validator'
  get 'mentions', to: 'users#mentions'
  get 'calendar', to: 'calendars#host'  # Esta ruta apuntará al método 'user' del controlador 'CalendarsController'

  post '/create_auto_tasks', to: 'tasks#create_auto_tasks', as: :create_auto_tasks

  resources :tasks, only: [:index, :create, :edit, :update, :destroy]
  # post 'clubs/:club_id/create_approved_membership/:user_id', to: 'clubs#create_approved_membership', as: :create_approved_membership


end
 

app/models/membership.rb
class Membership < ApplicationRecord
  
  # attr_accessible :user_id, :club_id
  enum status: {Pending: 0, Approved: 1, Declined: 2}

  belongs_to :club
  belongs_to :user

  # validates_uniqueness_of :user_id, :message => "You can only join one group!"
  validates_uniqueness_of :user_id, :scope => [:club_id], :message => "You have already requested to join the team."

  validate :slug
  validate :firstname
  validate :lastname

  # has_many :notifications, as: :notifiable, dependent: :destroy
  has_many :notifications

end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController
	before_action :is_authorised, only: [:edit]
	before_action :set_club, except: [:index, :new, :create]
  before_action :set_membership, only: [:approve, :decline, :show]

	def show
	end

	def create
		@membership = current_user.memberships.build(club_id: params[:club_id])

	  respond_to do |format|
	    if @membership.save
				@memberships =  @club.memberships
				redirect_back(fallback_location: request.referer, notice: "Saved!")
	      format.js
	    else
			  flash[:error] = "Sorry. It is not possible."
			  redirect_back(fallback_location: request.referer)
	      format.js
	    end
	  end
	end

	def update
		if @membership.update(membership_params)
		  flash[:notice] = "Saved!"
		else
		  flash[:notice] = "Oops! Something went wrong."
		end
		redirect_back(fallback_location: request.referer)
	end

	# def destroy
	# 	@membership = @club.memberships.find(params[:id])
  #   @user = User.find(@membership.user_id)
  #   @club = Club.find(@membership.club_id)
	# 	@membership.destroy
  #   # charge(@membership.club, @membership)
	# 	flash[:notice] = "¡Membresia eliminada!"
	# 	redirect_back(fallback_location: request.referer)
	# end

	def destroy
	  @membership = Membership.find(params[:id])
	  @user = User.find(@membership.user_id)
	  @club = @membership.club
    Notification.create(recipient: @user, notification_type: 'rejected', sender: @club.user, content: "Your request for #{@club.slug} has been rejected.", url: club_path(@club.id), club_id: @club.id, category: 2, action: 3)
		@membership.destroy
	  if @membership.destroy
	    flash[:notice] = 'You have rejected the invitation!'
	  else
	    flash[:error] = 'The invitation could not be deleted.'
	  end
	  redirect_to console_path
	end

  def approve 
    @user = User.find(@membership.user_id)
    @membership.Approved!
    Notification.create(recipient: @user, notification_type: 'joined', sender: @club.user, content: "Your request for #{@club.slug} has been approved.", url: club_path(@club.id), club_id: @club.id, category: 2, action: 2)
    # charge(@membership.club, @membership)
		flash[:notice] = "Membership approved!"
		redirect_back(fallback_location: request.referer)
  end

  def decline
    @membership.Declined!
		flash[:alert] = "Membership denied!"

		redirect_back(fallback_location: request.referer)
  end



	private
    def set_club
        @club = Club.friendly.find(params[:club_id])
    end


    def set_membership
        @membership = Membership.find(params[:id])
    end

    def membership_params
      params.require(:membership).permit(:user_id, :club_id, :active, :slug, :firstname, :lastname, :status, :position, :number, :maker_id)
    end
end

app/helpers/memberships_helper.rb
module MembershipsHelper
end

app/views/memberships/shared/_active.html.erb
<%= simple_form_for([club, membership]) do |f| %>
	<%= f.hidden_field :active, value: true %>
	<button type="submit">
		Accept
	</button>
<% end %>

app/views/memberships/shared/_declined.html.erb
<% if current_user == @club.user %>
	<% @declins.each do |member| %>
		<tr>
		  <th class="text-center">
		  	<figure class="_avatar">
				<%= image_tag member.avatar.variant(resize_to_limit: [300, 300]), class: "_avatar _1" %>
			</figure>
		  </th>
		  <td>
		  	<%= link_to user_path(member), class:"_name" do %>
		  		<%= member.firstname %> <%= member.lastname %>
		  	<% end %>
		  	<%= link_to user_path(member), class:"_username" do %>
				<%= member.slug %>
			<% end %>
		  </td>
		  <td class="_number">
		  	<h2><%= member.number %></h2>
		  </td>
		  <td class="text-center">
		  	<% @decliners = member.memberships.where("memberships.status == 2 AND memberships.club_id == '#{@club.id}'") %>
		    <% @decliners.each do |membership| %>
		        <%= link_to approve_club_membership_path(@club, membership), class:"_btnfirst", method: :post do %>
		          <i class="bi bi-check-lg"></i>
		        <% end %> 
		        <%= link_to club_membership_path(@club, membership),class: "_btncancel", method: :delete, data: { confirm: '¿Estás seguro?' } do %>
		          <i class="bi bi-x-lg"></i>
		        <% end %> 
		    <% end %>
		  </td>
		</tr>
	<% end %>
<% end %>

app/views/memberships/shared/_form.html.erb
<% if current_user == @club.user  %>
	<%= simple_form_for([@club, @membership]) do |f| %>
		<div class="input-group mb-3">
			<label class="input-group-text" for="inputGroupSelect01">Concovar a </label>
			<%= f.select :user_id, no_members.map {|key, value| [key.slug, key.user_id]}, {}, class: "form-select form-select-lg" %>
			<%= f.submit "Crear", class: "btn btn-outline-secondary" %>
		</div>
	<% end %>
<% else %> 
	<h1>You are not part of the team</h1>
<% end %>

app/views/memberships/shared/_members.html.erb
<% @members.each do |member| %>
	<tr>
	  <th class="text-center">
	  	<figure class="_avatar">
				<%= image_tag member.avatar.variant(resize_to_limit: [300, 300]), class: "_avatar _1" %>
			</figure>
	  </th>
	  <th class="_number">
	  	<h2><%= member.number %></h2>
	  </th>
	  <td>
	  	<%= link_to user_path(member), class:"_name" do %>
	  		<%= member.firstname %> <%= member.lastname %>
	  	<% end %>
	  	<%= link_to user_path(member), class:"_username" do %>
				<%= member.slug %>
			<% end %>
	  </td>
	  <td>
			<div class="btn-group dropstart" >
				<a class="" href="#" data-bs-toggle="dropdown" aria-expanded="false">
					<i class="bi bi-three-dots-vertical"></i>
				</a>
				<% @clubembers = member.memberships.where("memberships.status == 1 AND memberships.club_id == '#{@club.id}'") %>
				<% @clubembers.each do |membership| %>
				  <ul class="dropdown-menu">
				    <li>
				    	<%= link_to user_path(member), class: "dropdown-item", target: "_blank" do %>
				    		<span>View profile</span>
				    	<% end %>
				    </li>
				    <% if current_user == @club.user %>
					    <li>
					    	<%= link_to decline_club_membership_path(@club, membership), class:"dropdown-item", method: :post do %>
				    			<span>Suspend</span>
					    	<% end %>
					    </li>
				    <% end %>
				    <li>
				    	<%= link_to decline_club_membership_path(@club, membership), class:"dropdown-item", method: :post do %>
			    			<span>Report</span>
				    	<% end %>
				    </li>
				  </ul>
				<% end %>
			</div>
	  </td>
	</tr>
<% end %>

app/views/memberships/shared/_no_members.html.erb
<% if current_user == @club.user %>
	<% @no_members.each do |member| %>
		<tr>
		  <th class="text-center">
		  	<figure class="_avatar">
					<%= image_tag member.avatar.variant(resize_to_limit: [300, 300]), class: "_avatar _1" %>
				</figure>
		  </th>
		  <td>
		  	<%= link_to user_path(member), class:"_name" do %>
		  		<%= member.firstname %> <%= member.lastname %>
		  	<% end %>
		  	<%= link_to user_path(member), class:"_username" do %>
				<%= member.slug %>
			<% end %>

		  </td>
		  <td class="_number">
		  	<h2><%= member.number %></h2>
		  </td>
		  <td class="text-center">
		  	<% @clubembers = member.memberships.where("memberships.status == 0 AND memberships.club_id == '#{@club.id}'") %>
		    <% @clubembers.each do |membership| %>
		        <%= link_to approve_club_membership_path(@club, membership), class:"_btnapprove", method: :post do %>
		          <i class="bi bi-check-lg"></i>
		        <% end %> 
		        <%= link_to decline_club_membership_path(@club, membership), class:"_btncancel", method: :post do %>
		          <i class="bi bi-x-lg"></i>
		        <% end %>
		    <% end %>
		  </td>
		</tr>
		
	<% end %>
<% end %>

app/views/memberships/shared/_status.html.erb
<% if current_mocker.voted_up_on? mock %>
	<i class="fas fa-heart _like_color"></i>
<% else %>
	<i class="fas fa-heart"></i>
<% end %>