config/routes.rb
Rails.application.routes.draw do

  authenticated :user do
    root to: 'pages#console', as: :authenticated_root
  end

  unauthenticated do
    root to: 'pages#radar', as: :unauthenticated_root
  end

  resources :fields

  resources :users, only: [:show] do
    resources :goals, only: [:new, :create]
    resources :calendars
    member do
      post '/verify_phone_number' => 'users#verify_phone_number'
      patch 'update_phone_number' => 'users#update_phone_number'
      put 'follow' => 'users#follow'
      put 'unfollow' => 'users#unfollow'
      get 'clubs'
      get 'calledup'
      get 'view'
      get 'referee'
      get 'preview'
    end
  end
  resources :referees do
    member do
      get 'feed'
    end
  end
  resource :relationships, only: [:create, :destroy]
  resources :clubs, except: [:edit] do
    resources :invitations, only: [:new, :create]
    resources :calendars
    member do
      get 'edit'
      get 'duels'
      get 'members'
      get 'location'
      get 'scouting'
      get 'requests'
      get 'direction'
    end

    get 'join', on: :member
    get 'jointrue', on: :member
    post 'mark_all_as_read'
    post 'sendjoin/:user_id', to: 'clubs#sendjoin', as: 'sendjoin'
    post 'selfjoin/:user_id', to: 'clubs#selfjoin', as: 'selfjoin'

    resources :club_photos, only: [:create, :destroy]
    resources :memberships, only: [:create, :destroy, :edit, :update, :approve, :decline, :show] do 
      
      member do 
        post 'approve'
        get 'approve' 
        post 'decline' 
        get 'decline' 
      end
    end
    
    resources :duels do
      post :send_invitation, on: :member
      post 'join', on: :member
      get 'referee_access', on: :member
      get 'joinlines', on: :member
      resources :reservations, except: [:index, :new, :create]
      resources :invitations
      resources :duel_photos, only: [:create, :destroy]
      resources :rivals do
        post 'challenge', on: :collection
      end
      resources :reservations do 
        get 'reply'
      end
      resources :lines, only: [:create, :destroy, :edit, :update, :invoke, :ejected, :show] do 
        get 'join', on: :member
        get 'joinlines', on: :member
        member do 
          post '/invoke' => "lines#invoke"
          post '/ejected' => "lines#ejected"
        end
      end
      member do
        get 'front'
        get 'budget'
        get 'referee'
        get 'location'
        get 'panel'
        get 'members'
        get 'formation'
        get 'assignment'
        get 'control'
      end
    end
  end

  devise_for :users,
              path: '',
              path_names: {
                sign_in: 'login', 
                sign_out: 'logout', 
                edit: 'users/:id/edit',
                sign_up: 'registration' 
              }, 
              controllers: {
                omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations'
              }

  resources :notifications do
    member do
      patch :mark_as_read
    end
    
    collection do
      patch :mark_all_as_read
    end
  end



  get 'live' => 'pages#live'
  get 'radar' => 'pages#radar'
  get 'search' => 'pages#search'
  get 'battle' => 'pages#battle'
  get 'explore' => 'pages#explore'
  get 'console' => 'pages#console'
  get 'players' => 'pages#players'
  get 'notifications' => 'pages#notifications'
  get 'preload_tasks', to: 'pages#preload_tasks'
  get 'clubname_validator/:slug', to: 'clubs#clubname_validator'
  get 'username_validator/:slug', to: 'users#username_validator'
  get 'mentions', to: 'users#mentions'
  get 'calendar', to: 'calendars#host'  # Esta ruta apuntará al método 'user' del controlador 'CalendarsController'

  post '/create_auto_tasks', to: 'tasks#create_auto_tasks', as: :create_auto_tasks

  resources :tasks, only: [:index, :create, :edit, :update, :destroy]
  # post 'clubs/:club_id/create_approved_membership/:user_id', to: 'clubs#create_approved_membership', as: :create_approved_membership


end
 

app/views/shared/news/_message.html.erb
<% unless flash.empty? %>
	<script type="text/javascript">
		<% flash.each do |key, value| %>
			<% type = key.to_s.gsub('alert', 'error').gsub('notice', 'success') %>
			toastr['<%= type %>']('<%= value %>')
		<% end %>
	</script>
<% end %>

app/views/shared/news/_notification.html.erb
<div class="notification <%= 'off' if !notification.read_at.nil? %>">
  <div class="_in">
    <div class="_1">
      <div class="_i">
        <p class="_mutted"><%= notification.category_name %></p>
      </div>
      <div class="_ii">
        <p class="_mutted"><%= notification.time_remaining %> ago</p>
      </div>
    </div>
    <div class="_2">
      <h5 class="_content"><%= notification.content %></h5>
    </div>
    <div class="_3">
      <div class="_data">
        <% if notification.action_name == 'Amistad' %>
          <figure>
            <i class="fad fa-user-friends"></i>
          </figure>
          <p class="_annun">New friendship</p>
        <% elsif notification.action_name == 'Fan' %>
          <figure>
            <i class="fad fa-user-plus"></i>
          </figure>
          <p class="_annun">New follower</p>
        <% elsif notification.action_name == 'Convocatoria' %>
          <figure>
            <i class="fad fa-flag-checkered"></i>
          </figure>
          <p class="_annun">You have been called up</p>
        <% elsif notification.action_name == 'Aceptado' %>
          <figure>
            <i class="fad fa-check-circle"></i>
          </figure>
          <p class="_annun">Approved</p>
        <% elsif notification.action_name == 'Denegado' %>
          <figure>
            <i class="fad fa-times-circle"></i>
          </figure>
          <p class="_annun">Denied</p>
        <% elsif notification.action_name == 'Suspendido' %>
          <figure>
            <i class="fad fa-ghost"></i>
          </figure>
          <p class="_annun">New suspension</p>
        <% elsif notification.action_name == 'Solicitud' %>
          <figure>
            <i class="fad fa-hand-peace"></i>
          </figure>
          <p class="_annun">New request</p>
        <% elsif notification.action_name == 'Lesion' %>
          <figure>
            <i class="fad fa-user-injured"></i>
          </figure>
          <p class="_annun">Injury alert</p>
        <% elsif notification.action_name == 'Sancion' %>
          <figure>
            <i class="fad fa-engine-warning"></i>
          </figure>
          <p class="_annun">Sanction alert</p>
        <% elsif notification.action_name == 'Bloqueo' %>
          <figure>
            <i class="fad fa-ban"></i>
          </figure>
          <p class="_annun">Block alert</p>
        <% elsif notification.action_name == 'Invitacion' %>
          <figure>
            <i class="fad fa-envelope-open-text"></i>
          </figure>
          <p class="_annun">Invitación</p>
        <% elsif notification.action_name == 'Desafios' %>
          <figure>
            <i class="fad fa-swords"></i>
          </figure>
          <p class="_annun">Challenge</p>
        <% end %>
      </div>
    </div>
    </div>
    <% if notification.url %>
      <%= link_to mark_as_read_notification_path(notification), method: :patch, class: "_link_hide" do %><% end %>
    <% end %>
</div>